const TEXTS = [
  "A boot is the nail of a revolver. The first ungloved treatment is, in its own way, a suggestion. However, authors often misinterpret the roof as a presto size, when in actuality it feels more like a greenish tendency. It's an undeniable fact, really; muggy australians show us how headlines can be oceans. A pie can hardly be considered a churchy soy without also being a veterinarian. Some shocking deliveries are thought of simply as lumbers. Lunges are twinning sociologies. The inspired slice comes from a boundless nail. The estimate of a lip becomes a nervate low. Authors often misinterpret the number as a cornered frog, when in actuality it feels more like a solus pillow.",
  "Some posit the rayless hip to be less than grayish. Canty bags show us how maths can be buffers. A pickle is the mole of a bottom. Far from the truth, a stepson of the price is assumed to be an agape japanese. A stumbling range is a soap of the mind. Their umbrella was, in this moment, a punctate start. A william is a patient from the right perspective. The first spiffy leo is, in its own way, a passbook. They were lost without the spiry decade that composed their rabbi. Clippers are croupy bulldozers.",
  "To be more specific, the clefs could be said to resemble wreathless celsiuses. To be more specific, an arrow is a hammer from the right perspective. Their van was, in this moment, a thirstless sack. To be more specific, we can assume that any instance of a cockroach can be construed as a wanning daffodil. A city is a governor's viola. Recent controversy aside, the silica is a banana. If this was somewhat unclear, authors often misinterpret the drama as a turgid acknowledgment, when in actuality it feels more like an unplanked rhythm. This is not to discredit the idea that some soapless hots are thought of simply as luttuces. Far from the truth, an inborn panty is a deodorant of the mind. A pancreas of the current is assumed to be a superb arm.",
  "Unfortunately, that is wrong; on the contrary, a hippopotamus of the step-son is assumed to be a froward gearshift. A weight is a taming decision. What we don't know for sure is whether or not their spring was, in this moment, a statued cave. Saxophones are western flutes. The first gemmy workshop is, in its own way, a metal. A pudgy capital is a quiver of the mind. Far from the truth, those productions are nothing more than volcanos. It's an undeniable fact, really; the vase is an icicle. A thistle is a step-aunt's onion. The literature would have us believe that an adust hospital is not but a scraper.",
  "The flaming territory comes from a concave weed. In recent years, a reaction is the business of an anthony. The zone of a transaction becomes a dimply boy. Authors often misinterpret the ex-wife as a breathy jennifer, when in actuality it feels more like a sequined attack. Few can name a headfirst competitor that isn't a faunal quince. The platinum of a religion becomes a biggish algeria. Nowhere is it disputed that a falser carriage's macaroni comes with it the thought that the wider hyacinth is a fox. A stage is a scrappy nancy. Nowhere is it disputed that a monstrous case's veil comes with it the thought that the untailed fat is a guilty. If this was somewhat unclear, a sectile second without yugoslavians is truly a museum of nettly blues.",
  "The walk of a marimba becomes a trifid insect. If this was somewhat unclear, the literature would have us believe that a saltish december is not but a library. A melic lead's arch comes with it the thought that the prayerless methane is a font. Extending this logic, we can assume that any instance of a patient can be construed as a nitid driver. A peer-to-peer is the shoe of a gender. It's an undeniable fact, really; few can name an unsure illegal that isn't a sunlit tsunami. Before saves, oils were only vans. Barbers are sural visitors. The literature would have us believe that a spokewise propane is not but a saxophone. What we don't know for sure is whether or not a fustian flight's promotion comes with it the thought that the nineteen rice is a yoke.",
  "An ikebana can hardly be considered a convict window without also being a taurus. Few can name an averse needle that isn't a sylphic client. If this was somewhat unclear, the pursy spandex reveals itself as a glibbest wire to those who look. In ancient times some posit the afoot ATM to be less than cursing. We know that their brochure was, in this moment, an agog kimberly. A soda can hardly be considered a snowlike cathedral without also being a repair. Authors often misinterpret the belt as a tonish order, when in actuality it feels more like an awestruck butcher. We know that a mother-in-law of the footnote is assumed to be a chiseled butcher. Those goals are nothing more than selections. Extending this logic, a traffic is an occult actor.",
  "An intense temperature without gliders is truly a toenail of finest bedrooms. The karens could be said to resemble unused pastries. Before ties, operas were only willows. Far from the truth, the literature would have us believe that a pungent weapon is not but a riddle. Far from the truth, some eating necks are thought of simply as deposits. A finer centimeter's beauty comes with it the thought that the fourteenth ptarmigan is a vinyl. A history is an ovine bubble. The zeitgeist contends that the physician of a europe becomes a splanchnic quince. Those slaves are nothing more than births. Recent controversy aside, their step-mother was, in this moment, an unsoaped commission.",
  "Unfortunately, that is wrong; on the contrary, a swing sees a sister-in-law as an onward pillow. If this was somewhat unclear, a wash of the selection is assumed to be a seismic error. We can assume that any instance of a baritone can be construed as a truncate caterpillar. Aftermaths are crustless bakeries. Nitid footballs show us how temperatures can be mountains. Unplanked diseases show us how shakes can be umbrellas. Afeared toasts show us how cries can be languages. A hair sees a jar as a hammy existence. Some assert that an epoxy is an urnfield donna. Those washers are nothing more than beeches.",
  "The literature would have us believe that an immune oxygen is not but a fireman. This is not to discredit the idea that a weeny fur's c-clamp comes with it the thought that the wakerife custard is a crayfish. The ireful node comes from an adunc silk. A silk is the cell of a scanner. Some spokewise ravens are thought of simply as quotations. A spaghetti is a hither edge. We can assume that any instance of a brush can be construed as a tuneless thermometer. Their freon was, in this moment, a seismic mountain. The step-brothers could be said to resemble habile ATMS. We can assume that any instance of an ex-husband can be construed as a genty relative.",
  "If this was somewhat unclear, the scungy frown reveals itself as an hourly oyster to those who look. We know that an algeria of the parcel is assumed to be an alert bench. The first mono head is, in its own way, a sideboard. A verdict of the scarf is assumed to be a windy russian. Few can name a lurdan vinyl that isn't a rowdy basin. The literature would have us believe that a hearties taiwan is not but a melody. We can assume that any instance of a heaven can be construed as a burly history. The muggy television comes from a mural stopsign. One cannot separate shakes from ripping nurses. Those horns are nothing more than roots.",
  "A support can hardly be considered a setose volcano without also being a thunderstorm. A tadpole sees a calculus as a glairy brother. A treatment sees a celeste as a freest fiber. If this was somewhat unclear, before golds, buns were only tabletops. A jury is a curly fragrance. A rhythm is the doctor of an argument. Some assert that a rosy wine is a pint of the mind. The first unbid birth is, in its own way, an ornament. A yugoslavian is a haloid flock. In modern times some posit the creasy lumber to be less than shopworn.",
  "Though we assume the latter, the verdant dad reveals itself as a feeblish hope to those who look. In recent years, a soapy toilet's australian comes with it the thought that the roofless mother is a snow. The first fading refund is, in its own way, a bat. Extending this logic, some posit the valvar timbale to be less than veiny. The first gimcrack slip is, in its own way, a barge. They were lost without the chalky drug that composed their crate. We know that the accordions could be said to resemble houseless indonesias. The fiber of a soap becomes a neighbour mattock. The hate of a cloakroom becomes a doubling plain. Some unwarned dolls are thought of simply as qualities.",
  "The first cardboard boy is, in its own way, a client. Those stingers are nothing more than properties. A trumpet sees a beach as a rimy cable. A bait is the pheasant of an impulse. The estranged judo reveals itself as a sleeky brazil to those who look. A weather is a bloodied windscreen. Framed in a different way, authors often misinterpret the bow as a wisest record, when in actuality it feels more like a distraught donald. An explanation of the romanian is assumed to be a painless onion. A suit sees a work as a queenly play. In ancient times a colony is a tree's node.",
  "Authors often misinterpret the alto as a freebie plywood, when in actuality it feels more like an apeak banjo. In recent years, before juries, heliums were only afterthoughts. It's an undeniable fact, really; a seal sees an equinox as an unwon leaf. An aching ton without catamarans is truly a continent of glummer revolvers. Some posit the dovish seeder to be less than weekday. A pollution can hardly be considered a priestly editorial without also being an elbow. Their risk was, in this moment, a naughty lan. A gearshift is a swordlike jump. Framed in a different way, the fibre of a craftsman becomes a honeyed hope. Authors often misinterpret the level as a venous recorder, when in actuality it feels more like a boring addition.",
];

export default function getRandomText(): string {
  return TEXTS[Math.floor(Math.random() * TEXTS.length)];
}
